### PR TITLE
make iTerm scripts work with iTerm 2.9

### PR DESCRIPTION
**Pull request by vitorgalvao**
This is in continuation to https://github.com/LeEnno/alfred-terminalfinder/pull/11. It now uses the code for iTerm 2.9. Even though that isn’t yet in stable, the code for 2.1 stopped working correctly, for some reason. Having the code for the future version might be preferable for that reason.

As for the oddity it might seem to refer to the app as both `iTerm2` and `iTerm`, that is the only way it seems to work. When looking for if the app is running, `iTerm` doesn’t work, but `iTerm2` works; however, when giving instructions to the app, the reverse is true.

### CODE REVIEW

**Comment by LeEnno** [comment]
Thx for another pull request.

Instead of completely getting rid of support for iTerm < 2.9, I'd rather introduce a backwards compatible approach. This will be quite complex in the end but hopefully work for all users.

**Comment by jguice** [comment]
iTerm(2) seems to be in a state of partial renaming.  The app menu bar shows 'iTerm2' but the dock still says 'iTerm'.  Hopefully @gnachman will sort it out for the final release. :smiley:

**Comment by jguice** [comment]
@vitorgalvao take a look at #13.  I linked a SO thread that talks about ways to detect different kinds of app "presence" (e.g. installed, running).

**Comment by LeEnno** [comment]
FYI: I'd rather go with a feature detection technique than relying on file names oder app versions. So I will probably do some try/catch thingy with testing the old API and the new one.

**Comment by vitorgalvao** [comment]
@jguice Thank you, but I already know how to do that. The issue here is version detection.

Although, now that I think about it, since iTerm 2.9 requires the `iTerm2` name to confirm it is running, checking the version might have just become easier as a side effect.

**Comment by jguice** [comment]
Heh, exactly.  For now you can differentiate between the two by name I think. :wink:

**Comment by jguice** [comment]
@LeEnno if you'd rather, this works too:
```applescript
get version of application "iTerm"
```

**Comment by LeEnno** [comment]
Will have a look, thx

**Comment by gnachman** [comment]
I've renamed it from iTerm to iTerm2 everywhere except the app's folder, which I can't change for existing users anyway. Since the bundle name has changed to iTerm2, version 2.9+ will respond to that for applescript. I believe your best bet is to check the version number.

**Comment by vitorgalvao** [comment]
To be clear, I don’t intend on working on this PR further, for various reasons (mainly that I do not think it is worth it, for the available time I have), but anyone is free to take the submitted code in any way, shape, or form, to develop a working solution.

[A first try was made previously](https://github.com/LeEnno/alfred-terminalfinder/pull/11#issuecomment-153389294). I though I had submitted that reply here, but noticed now I posted to the wrong issue.

**Comment by gnachman** [comment]
For anyone who wishes to take this up, I believe you'll need to do something along the lines of
````
if (old_version) {
  run script ("...old script goes here...")
} else {
  run script ("...new script goes here...")
}
````
Because the two versions use different applescript codes and can't coexist outside of a `run script`.

**Comment by LeEnno** [comment]
[The newest version](https://github.com/LeEnno/alfred-terminalfinder/blob/master/TerminalFinder.alfredworkflow?raw=true) should be working with iTerm 2.9.x.

I tried a backwards compatible approach and nearly had it down but failed due to some kind of caching issue in Alfred. I probably could have gotten around it, but doing the same thing for Path Finder support and all the other little details was just too much.

Thanks for your reports, comments and suggestions. Despite this pull request I went [with my own take](https://github.com/LeEnno/alfred-terminalfinder/commit/ca8f5a72f60b9e5ec4521b61b1df635fd93392c5#diff-f13747d16fb444aebadefcad504f9674) on it, since it's a little cleaner.

**Comment by jguice** [comment]
Awesome!  Thanks everyone :-)

**Pull request closed without merging**
